env = Environment()

env['APP_TARGET'] = 'ciUISaveLoadSettingsApp'
env['APP_SOURCES'] = ['ciUISaveLoadSettingsApp.cpp']

# ciUI block
env = SConscript('../../../scons/SConscript', exports = 'env')

SConscript('../../../../../scons/SConscript', exports = 'env')

