env = Environment()

env['APP_TARGET'] = 'ciUIDynamicDropDownApp'
env['APP_SOURCES'] = ['ciUIDynamicDropDownApp.cpp']

# ciUI block
env = SConscript('../../../scons/SConscript', exports = 'env')

SConscript('../../../../../scons/SConscript', exports = 'env')

